name: attijari_digital
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
   sdk: flutter
  http: ^1.4.0
  flutter_credit_card: ^4.1.0
  local_auth: ^2.3.0
  flutter_keyboard_visibility: ^6.0.0
  image_picker: ^1.1.2
  vector_math: any 
  pinput: ^5.0.1
  provider: ^6.1.5+1



  cupertino_icons: ^1.0.8
  #firebase_core: ^2.24.2
  firebase_core_web: ^2.11.0
  firebase_core: ^3.15.1
  firebase_auth: ^5.6.2
  cloud_firestore: ^5.4.3  # if needed
  firebase_storage: ^12.3.2
  firebase_messaging: ^15.2.9
  flutter_local_notifications: ^19.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

 
  uses-material-design: true

  assets:
    #- assets/translations/
    - assets/logo.png
    - assets/image/appbar1.png
    - assets/attijari-bank.png
    - assets/carte/e_confort.png
    - assets/carte/essentiel_premium.jpg
    - assets/carte/pack_elan_gold_1.png
    - assets/carte/Particulier & Professions/Carte_ouverture_compte _18_25.jpg
    - assets/carte/Particulier & Professions/Essentiel_club.jpg 
    - assets/carte/Particulier & Professions/essentiel_premium.jpg
    - assets/carte/Particulier & Professions/Essentiel_titanium.jpg
    - assets/carte/Petite entreprise/entreprneur.png
    - assets/carte/e_confort.png
    - assets/carte/Petite entreprise/premier.png
    - assets/carte/Marocains/pack_elan_gold_1.png
    - assets/carte/Marocains/Pack_elan_gold.png
    - assets/carte/Marocains/Pack_platinium.png
    - assets/carte/Marocains/Pack_signature.png
    - assets/carte/atm-card.png
    

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
