// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKJPvyccmFnMAOFnznxKtWGEEsSuA4GNk',
    appId: '1:155148609778:web:b5f68e2fe2037ba7aac86b',
    messagingSenderId: '155148609778',
    projectId: 'attijari-digital',
    authDomain: 'attijari-digital.firebaseapp.com',
    storageBucket: 'attijari-digital.firebasestorage.app',
    measurementId: 'G-5HFEB91HZD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNfN4JgSc295E2EdyV0YasnY0CeNCN0g4',
    appId: '1:155148609778:android:dcb6b732cefb8e04aac86b',
    messagingSenderId: '155148609778',
    projectId: 'attijari-digital',
    storageBucket: 'attijari-digital.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTDjAUhi0q1NId39o21LyimXZnexCe7rY',
    appId: '1:155148609778:ios:4bd667ad2557c3d3aac86b',
    messagingSenderId: '155148609778',
    projectId: 'attijari-digital',
    storageBucket: 'attijari-digital.firebasestorage.app',
    iosBundleId: 'com.example.attijariDigital',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTDjAUhi0q1NId39o21LyimXZnexCe7rY',
    appId: '1:155148609778:ios:4bd667ad2557c3d3aac86b',
    messagingSenderId: '155148609778',
    projectId: 'attijari-digital',
    storageBucket: 'attijari-digital.firebasestorage.app',
    iosBundleId: 'com.example.attijariDigital',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKJPvyccmFnMAOFnznxKtWGEEsSuA4GNk',
    appId: '1:155148609778:web:5d99fcfe59d5f747aac86b',
    messagingSenderId: '155148609778',
    projectId: 'attijari-digital',
    authDomain: 'attijari-digital.firebaseapp.com',
    storageBucket: 'attijari-digital.firebasestorage.app',
    measurementId: 'G-7DZZ00HC1C',
  );
}
